In [1]:
import pandas as pd

In [4]:
data = pd.read_csv("wordnet_results-14012022-19-16-55.csv")

In [6]:
data[data.word=='owl']

,Unnamed: 0,norm_recall,norm_distance,cos_recall,cos_distance,original_recall,original_distance,definition,word
9687,9687,"['hawk', 'bird', 'fox', 'snake', 'birds', 'eag...",[1.7049384 1.7067298 1.7022897 ... 1.9511259 1...,"['277', '510', '321', '404', '269', '268', '77...",[0.6336487 0.62889665 0.62577575 0.62195545 0...,"['owls', '1779', '1795', '1675', '1672', '1738...",[0.7283466 0.62349284 0.6173864 0.6096438 0...,nocturnal bird of prey with hawk-like beak and...,owl

In [7]:
data[data.word=='butte']

,Unnamed: 0,norm_recall,norm_distance,cos_recall,cos_distance,original_recall,original_distance,definition,word
6421,6421,"['mountain', 'mountains', 'plateau', '1982', '...",[1.185877 1.1765275 1.1706028 ... 1.3709185 1...,"['plateau', 'hilltop', '1682', '1679', '1699',...",[0.65169626 0.6509792 0.647647 0.6470854 0...,"['1628', '1641', '1790', '1738', '1740', '1760...",[0.6392355 0.63468343 0.63292575 0.6318631 0...,a hill that rises abruptly from the surroundin...,butte

In [10]:
data.sample(10)

,Unnamed: 0,norm_recall,norm_distance,cos_recall,cos_distance,original_recall,original_distance,definition,word
10989,10989,"['1982', 'egypt', '1996', '1958', '1988', '193...",[1.0096614 1.0063837 1.0169638 ... 1.2010263 1...,"['1738', 'greeks', '1829', '1797', 'mesopotami...",[0.6288939 0.6227824 0.61669135 0.61622876 0...,"['1672', '1712', '1682', '1703', '1711', '1695...",[0.67562795 0.6685985 0.667594 0.66636276 0...,the largest Greek island in the Mediterranean;...,crete
12091,12091,"['increased', 'decreased', 'increase', 'consid...",[0.8446653 0.84337795 0.8283458 ... 1.075547...,"['decreases', 'decrease', 'sizable', 'expands'...",[0.6921073 0.6848613 0.6799243 0.67970043 0...,"['totaling', 'totals', '[unused916]', '[unused...",[0.79238725 0.6938672 0.6916542 0.69116294 0...,add up in number or quantity,totaled
457,457,"['bangalore', '[unused139]', '[unused948]', '[...",[0.729548 0.7201662 0.7160309 ... 1.0712996 1...,"['hyderabad', 'lucknow', '[unused139]', '[unus...",[0.7624245 0.75628406 0.75411254 0.7536265 0...,"['ahmedabad', 'mysore', 'mumbai', 'hyderabad',...",[0.7126507 0.7117328 0.6989815 0.698825 0...,an industrial city in south central India (wes...,bangalore
11729,11729,"['percy', '[unused527]', '[unused769]', '[unus...",[0.7899786 0.79652524 0.79241735 ... 1.015355...,"['1747', '1738', '1744', '1746', '1827', '1721...",[0.69052833 0.67818546 0.67808247 0.6774743 0...,"['northumberland', '1779', 'ᄐ', '1759', '1780'...",[0.60072494 0.5998782 0.5930309 0.59278876 0...,United States writer whose novels explored hum...,percy
3014,3014,"['[unused295]', '[unused769]', '[unused845]', ...",[0.8559592 0.8668559 0.85457885 ... 1.112127...,"['[unused295]', '[unused198]', '[unused293]', ...",[0.65815777 0.6580777 0.65791327 0.6577265 0...,"['sinking', 'sank', 'sinks', 'sunken', 'sink',...",[0.74588007 0.72048545 0.70278937 0.641835 0...,fall or descend to a lower place or level,sunk
6213,6213,"['girl', 'woman', 'miss', 'girls', 'boy', 'man...",[2.0724304 2.0636578 2.0523844 ... 2.2012105 2...,"['girl', 'woman', 'lady', 'boy', 'girls', 'man...",[0.59012765 0.5038873 0.4528684 0.44995093 0...,"['girls', 'boy', 'woman', 'boys', 'female', 'w...",[0.7141131 0.699876 0.6869456 0.5659368 0...,a young woman,girl
8497,8497,"['[unused706]', '[unused203]', '[unused359]', ...",[0.7299279 0.72099686 0.7244037 ... 0.973814...,"['franchises', '1670', '1695', '1712', '1623',...",[0.7177499 0.7166229 0.7163542 0.7153902 0...,"['franchises', '[unused935]', 'relocate', '[un...",[0.7973199 0.49691066 0.49606282 0.4954124 0...,an authorization to sell a company's goods or ...,franchise
7746,7746,"['sadness', '1913', 'anxiety', 'despair', 'fru...",[0.80464613 0.8062631 0.79965645 ... 1.008317...,"['1739', '1752', '1638', '1712', 'resentment',...",[0.7313026 0.7300604 0.729996 0.7299711 0...,"['nerve', 'nervous', 'insides', 'hormones', '[...",[0.62060606 0.6202373 0.5975206 0.58997697 0...,an uneasy psychological state,nerves
13669,13669,"['create', 'technology', '1982', 'construction...",[1.0972903 1.0936952 1.0838627 ... 1.2510424 1...,"['1682', '1630', '273', '670', '1726', '1628',...",[0.6342345 0.6314377 0.6305267 0.6303812 0...,"['1726', '1736', '1727', '1723', '1718', '1692...",[0.6632884 0.6592884 0.657351 0.65505576 0...,the fundamental assumptions from which somethi...,cornerstone
10114,10114,"['[unused613]', '1878', '[unused261]', '[unuse...",[0.74553573 0.7446443 0.7449685 ... 1.046025...,"['1712', '1697', '1682', '1711', '1747', '1705...",[0.7694738 0.766199 0.76611453 0.76553905 0...,"['caliphate', '[unused252]', '[unused142]', '[...",[0.70043963 0.69426644 0.69397974 0.6939171 0...,country or territory ruled by a sultan,sultanate

In [11]:
def filter_words_by_norm(norm_range=(0, 1.2)):
    data = pd.read_csv("wordnet_bert_common_words.csv")
    words = data[data.norms.apply(
        lambda x: norm_range[0] < x < norm_range[1])].words.values
    words = set(words.tolist())
    print(f">>>> There are {len(words)} words between norm range {norm_range}")
    return words

In [26]:
words = filter_words_by_norm((1.6, 2))
data[data.word.apply(lambda x: x in words)].to_csv('low_freq.csv')

>>>> There are 358 words between norm range (1.6, 2)

In [31]:
high_freq_data = data[data.word.apply(lambda x: x in words)].drop(columns=['Unnamed: 0'])

In [32]:
high_freq_data

,norm_recall,norm_distance,cos_recall,cos_distance,original_recall,original_distance,definition,word
10,"['germany', 'russia', 'italy', 'poland', 'fran...",[1.671895 1.6866046 1.6743553 ... 1.8581285 1...,"['poland', 'austria', 'russia', 'italy', 'swed...",[0.633815 0.6319068 0.6198112 0.61912113 0...,"['1665', 'munchen', '1747', '1664', '1697', '1...",[0.6815698 0.6809776 0.6779952 0.6760936 0...,a republic in central Europe; split into East ...,deutschland
91,"['ireland', 'senator', 'richard', 'angry', 'it...",[1.6850832 1.6929789 1.6753379 ... 1.8231254 1...,"['1845', '1774', '1858', '1849', '1679', 'dail...",[0.4702203 0.4698714 0.4692401 0.4670674 0...,"['1695', '1727', '1726', '1783', '1679', '1638...",[0.6310999 0.6281102 0.62630224 0.6244551 0...,the lower house of the parliament of the Irish...,dail
125,"['[unused69]', '[unused613]', '[unused615]', '...",[0.6844224 0.6961067 0.69106394 ... 0.986212...,"['1642', 'ᄅ', '[unused69]', '1643', '[unused61...",[0.74186796 0.7401238 0.7390986 0.73906356 0...,"['intervene', 'intervened', 'interfering', '17...",[0.72791624 0.72053367 0.68788165 0.6815716 0...,"get involved, so as to alter or hinder an acti...",intervening
202,"['[unused613]', '[unused74]', '[unused753]', '...",[0.6917931 0.6995655 0.69303024 ... 0.969563...,"['1699', '1762', 'kidnapping', '1721', '1798',...",[0.7371238 0.73624504 0.7355947 0.7349002 0...,"['breakthrough', '1781', '1797', '1703', '1798...",[0.7127022 0.6887165 0.6806261 0.6801952 0...,an escape from jail,breakout
243,"['violin', 'clarinet', 'violinist', 'saxophone...",[1.2530257 1.2612753 1.2517369 ... 1.4830601 1...,"['clarinet', 'saxophone', 'violinist', 'flute'...",[0.6754372 0.66413623 0.66371 0.6413993 0...,"['1764', 'oboe', '1765', '1704', '1754', '1717...",[0.64878213 0.6455357 0.6422614 0.63866836 0...,a small flute; pitched an octave above the sta...,piccolo
...,...,...,...,...,...,...,...,...
14403,"['guitar', 'violin', '14th', 'ninth', 'musicia...",[1.0051014 1.0081961 1.0077063 ... 1.1740048 1...,"['trumpeter', 'trumpet', '1682', 'violin', '17...",[0.67131805 0.6706684 0.66947484 0.66807085 0...,"['1738', '1732', '1734', '1741', '1743', '1742...",[0.7401216 0.7205515 0.7202167 0.71991 0...,the lowest brass wind instrument,tuba
14422,"['[unused613]', '[unused460]', '[unused266]', ...",[0.64548105 0.6433281 0.6389061 ... 0.896664...,"['[unused460]', '[unused266]', '[unused613]', ...",[0.73958284 0.73897326 0.738837 0.7386112 0...,"['exemplified', 'lauded', '1622', 'spearheaded...",[0.7070121 0.65503246 0.6530167 0.6519762 0...,represent in bodily form,embodied
14424,"['birmingham', 'atlanta', 'chicago', 'johnson'...",[0.98568416 0.98907477 0.98579985 ... 1.192449...,"['1747', 'ذ', '##ذ', '1822', '1762', '1779', '...",[0.654335 0.653376 0.65327835 0.65254945 0...,"['1736', '1727', '1774', '1570', '1754', '1756...",[0.64159757 0.63863057 0.6375282 0.6361989 0...,a town in central Alabama on the Alabama river...,selma
14488,"['directly', 'frequently', 'quickly', 'constan...",[1.0974648 1.1010056 1.0947797 ... 1.3223566 1...,"['1634', '1635', 'continually', '1708', '1705'...",[0.6437464 0.64254 0.64206 0.6405205 0...,"['immensely', 'vastly', 'amazingly', 'infinite...",[0.6771044 0.66702026 0.6656906 0.66509545 0...,without bounds,infinitely
14489,"['pakistan', '1878', '[unused21]', '[unused935...",[0.8540726 0.86301035 0.849195 ... 1.164570...,"['maharashtra', '1679', '1682', 'peshawar', '1...",[0.71299005 0.71169907 0.7115032 0.7100696 0...,"['1746', '1782', '1628', '1642', '1738', '1727...",[0.70293164 0.70027727 0.6974155 0.69711554 0...,a city in northern India; former capital of th...,agra

In [34]:
from nltk.corpus import wordnet as wn

In [39]:
wn.synsets('dog')[0].lemma_names('cmn')

['犬', '狗']

- [ ] 取出来50个词，精简recall，让 recall 尽可能只含有单词。
- [x] 去掉所有 unusedxxx 
- [x] 塞选出所有的名词

In [44]:
wordnet_nouns = list(wn.all_lemma_names(pos='n', lang='eng'))

In [47]:
all_nouns = high_freq_data[high_freq_data.word.apply(lambda x: x in wordnet_nouns)]

In [52]:
excluded_unusesed = all_nouns[all_nouns.norm_recall.apply(lambda x: 'unused' not in x)]

- [ ] 对 word 进行中文翻译

In [64]:
excluded_unusesed['translate'] = excluded_unusesed.word.apply(lambda x: wn.synsets(x)[0].lemma_names('cmn'))

/tmp/ipykernel_3069215/3465263129.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  excluded_unusesed['translate'] = excluded_unusesed.word.apply(lambda x: wn.synsets(x)[0].lemma_names('cmn'))

In [368]:
'ggg'''''''.replace('\'', '')

'ggg'

In [409]:
def filter_numbers(x):
    x = x.replace('\'', '').replace('[', '').replace(']', '').replace(' ','')
    word_count = 0
    words = []
    for word in x.split(','):
        if not word.isdigit():
            word_count += 1
            words.append(word)
    return word_count > 5
filter_numbers_df = excluded_unusesed[excluded_unusesed.norm_recall.apply(filter_numbers)]

In [410]:
filter_numbers_df

,norm_recall,norm_distance,cos_recall,cos_distance,original_recall,original_distance,definition,word,translate
10,"['germany', 'russia', 'italy', 'poland', 'fran...",[1.671895 1.6866046 1.6743553 ... 1.8581285 1...,"['poland', 'austria', 'russia', 'italy', 'swed...",[0.633815 0.6319068 0.6198112 0.61912113 0...,"['1665', 'munchen', '1747', '1664', '1697', '1...",[0.6815698 0.6809776 0.6779952 0.6760936 0...,a republic in central Europe; split into East ...,deutschland,[]
91,"['ireland', 'senator', 'richard', 'angry', 'it...",[1.6850832 1.6929789 1.6753379 ... 1.8231254 1...,"['1845', '1774', '1858', '1849', '1679', 'dail...",[0.4702203 0.4698714 0.4692401 0.4670674 0...,"['1695', '1727', '1726', '1783', '1679', '1638...",[0.6310999 0.6281102 0.62630224 0.6244551 0...,the lower house of the parliament of the Irish...,dail,[]
1314,"['k', 's', 'm', 'a', 'b', 'the', 'c', 'i', 'g'...",[2.2440157 2.2544851 2.2408824 ... 2.363615 2...,"['m', 'b', 'g', 'c', 's', 'r', 'e', 'd', 'f', ...",[0.5060683 0.5053469 0.4843874 0.4822059 0...,"['1560', '1761', '1760', '1757', '1665', '1811...",[0.62193143 0.6100152 0.6079467 0.60489887 0...,the basic unit of thermodynamic temperature ad...,kelvin,[开尔文]
2086,"['wilson', 'william', 'thomas', 'john', 'johns...",[1.1298183 1.1333636 1.1171696 ... 1.313281 1...,"['1785', '1827', '1786', '1822', '1809', '1716...",[0.58619875 0.58534914 0.5851014 0.58331716 0...,"['1734', '1732', '1738', '1746', '1654', '1735...",[0.6859774 0.68553346 0.68231887 0.68117684 0...,leader in the women's suffrage movement in Mon...,rankin,[]
2641,"['pennsylvania', 'maryland', 'michigan', 'cali...",[0.8747794 0.8703409 0.8741758 ... 1.1084973 1...,"['1692', '1699', '1664', '1738', '1695', '1779...",[0.7130301 0.7115049 0.7111702 0.7085853 0...,"['1732', '1738', '1747', '1736', '199', 'ᄐ', '...",[0.64960533 0.6451258 0.642288 0.6420925 0...,a Mid-Atlantic state on the Atlantic; one of t...,nj,[]
2959,"['beach', 'valley', 'river', '1986', 'lake', '...",[1.1570735 1.1527925 1.1534727 ... 1.3192135 1...,"['29th', '1699', '27th', '28th', 'shoreline', ...",[0.62801117 0.6201408 0.62003267 0.61993325 0...,"['1747', '213', '1752', '1672', '1746', '1749'...",[0.6176211 0.6082037 0.60772586 0.60751265 0...,a strip of land projecting into a body of water,ness,[]
3155,"['french', 'german', 'italian', 'russian', 'ca...",[1.116134 1.1190794 1.1075722 ... 1.2847538 1...,"['1747', '39th', '37th', '307', '1716', '1734'...",[0.6239635 0.623285 0.6231402 0.6227338 0...,"['1665', '1797', '1794', '1697', '1695', '1729...",[0.62781173 0.6242255 0.61599565 0.61368316 0...,a person of French descent,gaul,[]
3796,"['andrew', 'michael', 'sarah', 'daniel', 'rach...",[1.0035548 0.99789125 0.99849486 ... 1.201771...,"['joshua', 'jeremiah', 'andrew', 'timothy', 'e...",[0.60759777 0.604953 0.5990547 0.5957997 0...,"['1716', '1737', '1711', '1740', '1734', '1736...",[0.7143542 0.7127642 0.71235913 0.71178466 0...,(Old Testament) the 2nd son of Jacob and one o...,simeon,[]
3873,"['australia', 'malaysia', 'nigeria', 'brazil',...",[1.1001264 1.1050475 1.0998728 ... 1.2748946 1...,"['nigeria', 'uganda', 'kenya', 'malaysia', 'ic...",[0.6162337 0.61553013 0.6143866 0.6083497 0...,"['mauritius', 'maldives', 'bahamas', 'ச', 'gam...",[0.7545985 0.714705 0.7010408 0.69897485 0...,a republic on the Seychelles islands; achieved...,seychelles,[]
4057,"['horse', '1900', 'john', '1950', 'birds', 'do...",[1.7586482 1.7481642 1.7426333 ... 2.0257626 2...,"['820', '354', '292', '237', '480', '216', '32...",[0.6126532 0.6125697 0.61227685 0.6119746 0...,"['kochi', 'malabar', 'ᄎ', '1695', '1748', '178...",[0.70153695 0.6693869 0.64753574 0.64670956 0...,Asian breed of large fowl with dense plumage a...,cochin,[]
4437,"['michael', 'james', 'andrew', 'peter', 'willi...",[1.1368046 1.1326813 1.1299045 ... 1.3903906 1...,"['1762', '1755', '1609', '1721', '1628', '1740...",[0.6070818 0.60491276 0.60372424 0.6036155 0...,"['[unused359]', '[unused155]', '[unused260]', ...",[0.68414056 0.68411505 0.68405515 0.6833571 0...,bishop of Antioch who was martyred under the R...,ignatius,[]
4741,"['johnson', 'wilson', 'taylor', 'william', 'wi...",[1.2377048 1.2297316 1.2344456 ... 1.409087 1...,"['1764', '1742', '1770', '1762', '1743', '273'...",[0.58190733 0.5799157 0.576213 0.5754586 0...,"['323', '331', '1726', '1630', '257', '1779', ...",[0.67306864 0.6699416 0.6697533 0.6696717 0...,United States composer of musical comedies (18...,kern,[]
4748,"['an', 'the', 'he', 'she', 'students', 'john',...",[1.7020289 1.7135065 1.6850977 ... 1.803446 1...,"['201', '26th', '41st', '355', '196', '307', '...",[0.43347687 0.43072802 0.43032628 0.42974228 0...,"['1664', 'マ', '1661', '1665', 'ம', 'མ', 'ל', '...",[0.63497645 0.63450575 0.6343744 0.6342912 0...,a master's degree in fine arts,mfa,[]
5136,"['jerusalem', 'vienna', '1909', 'copenhagen', ...",[1.4265823 1.4183319 1.4144121 ... 1.7271178 1...,"['baghdad', 'bucharest', '1703', '1699', '1727...",[0.6548887 0.6514225 0.6490318 0.64669704 0...,"['1628', '1734', '1726', '1672', '1689', '1703...",[0.7154377 0.7069511 0.7056803 0.7014471 0...,the capital and largest city of Jordan,amman,[安曼]
5181,"['malaysia', 'thailand', 'cambodia', 'myanmar'...",[1.5855691 1.5934312 1.583186 ... 1.9179269 1...,"['malaysia', 'myanmar', 'cambodia', 'malaysian...",[0.64392793 0.6300115 0.62760836 0.6041996 0...,"['1797', '1794', '1795', 'ต', '1798', '[unused...",[0.701025 0.69964135 0.6942093 0.69302815 0...,a peninsula of southeastern Asia that includes...,indochina,[]
5212,"['beautiful', 'girl', 'richard', 'william', 'j...",[1.1541955 1.1552814 1.1497805 ... 1.3222909 1...,"['690', '1729', '317', '268', '1743', '1738', ...",[0.66561705 0.6648589 0.659654 0.6593848 0...,"['1773', '1682', '1643', '1712', '1675', '1713...",[0.6272518 0.6177805 0.61565554 0.6156052 0...,a desirable state,boon,[幸事]
5334,"['john', 'he', 'the', 'robert', '1982', 'willi...",[1.4622668 1.4595262 1.4593946 ... 1.6189252 1...,"['253', '178', '213', '243', '254', '189', '27...",[0.6228082 0.6207987 0.61992645 0.61856085 0...,"['1744', '1785', '1729', '1820', '1796', '1747...",[0.61162555 0.609321 0.60807985 0.60781556 0...,a radioactive gaseous element formed by the di...,rn,[氡]
5594,"['michigan', 'connecticut', 'vermont', 'califo...",[0.83718324 0.83515704 0.8372873 ... 1.107417...,"['1779', '1663', '1692', '1664', '1697', '1749...",[0.7482302 0.7475415 0.7469003 0.74656767 0...,"['1757', '1711', '1705', '1703', '1738', '1754...",[0.6822617 0.6685419 0.6681819 0.6678831 0...,a state in New England,vt,[]
5750,"['russia', 'russian', 'soviet', 'ukraine', 'mo...",[1.0341959 1.0407197 1.0401492 ... 1.2199447 1...,"['ussr', 'belarus', 'ukraine', 'soviets', 'rus...",[0.624714 0.6134378 0.6126916 0.59996486 0...,"['1738', '1612', '1697', '1764', '1732', '1654...",[0.5963455 0.5927567 0.5918196 0.58830357 0...,an alliance made up of states that had been So...,cis,[]
6252,"['soldiers', 'captain', 'colonel', 'lieutenant...",[1.1013415 1.0990226 1.0897303 ... 1.2744178 1...,"['lieutenant', 'commanders', '1733', '1749', '...",[0.5930531 0.5906799 0.5874956 0.58425355 0...,"['##ᄏ', '1704', '1642', '[unused895]', '[unuse...",[0.65252787 0.6451323 0.64464855 0.6441342 0...,a noncommissioned officer in the British artil...,bombardier,[]
6424,"['clothing', 'shirt', 'shoe', 'shoes', 'dress'...",[1.296454 1.2950114 1.2801771 ... 1.5681901 1...,"['skirt', '1729', '47th', '1712', '1736', 'thi...",[0.6193862 0.5964819 0.5964014 0.593368 0...,"['1718', 'socks', '1712', '1766', '1610', '34t...",[0.6293821 0.62337226 0.62015784 0.61616415 0...,hosiery consisting of a cloth covering for the...,sock,[袜子]
6447,"['july', 'september', 'june', 'january', 'nove...",[2.0258765 2.0403285 2.0089462 ... 2.1584632 2...,"['winter', 'september', 'july', 'december', 'j...",[0.5001185 0.49937677 0.4948089 0.49407977 0...,"['[unused138]', '[unused266]', '[unused519]', ...",[0.63268787 0.63196975 0.6318244 0.63132197 0...,"June 21, when the sun is at its northernmost p...",midsummer,"[仲夏, 盛夏]"
6560,"['vehicle', 'truck', 'car', 'vehicles', 'boat'...",[1.3609452 1.3666337 1.3610446 ... 1.4613131 1...,"['jeep', 'vehicle', 'automobiles', 'airplane',...",[0.57307106 0.5640297 0.55486196 0.5543103 0...,"['1675', '1634', '1738', '1651', '1756', '1611...",[0.697173 0.6896704 0.6889664 0.6863527 0...,a motorized wheeled vehicle used for camping o...,rv,[]
6746,"['princess', 'rachel', 'emily', 'richard', '19...",[1.3304226 1.3468959 1.3263407 ... 1.5444615 1...,"['1734', '1738', 'durga', 'ま', '1748', '1100',...",[0.5540126 0.55087656 0.5500087 0.547161 0...,"['1751', '1754', '1734', '1721', '1761', '1747...",[0.6852815 0.68302 0.6819128 0.679726 0...,(the feminine of raja) a Hindu princess or the...,rani,[]
6784,"['cologne', 'hamburg', 'stuttgart', 'leipzig',...",[1.2633339 1.2617432 1.253894 ... 1.596544 1...,"['hamburg', '1664', '1682', '1624', '1734', '1...",[0.7469675 0.7277489 0.72483975 0.7234722 0...,"['munchen', '1738', '1741', '33rd', '1731', '1...",[0.7278167 0.72357047 0.7198746 0.714679 0...,a commercial center and river port in western ...,koln,[]
7017,"['wilson', 'william', 'thompson', 'thomas', '1...",[1.0482066 1.0520723 1.0495197 ... 1.2371726 1...,"['1762', '1742', '1764', '1730', '1738', '1739...",[0.6745661 0.6738848 0.6716936 0.67084557 0...,"['1762', '1825', '1770', '1811', '1759', '1779...",[0.6420887 0.6399504 0.6389775 0.63841933 0...,United States naturalist (born in England) who...,muir,[]
7918,"['water', 'c', 'the', 'john', 'four', 'large',...",[1.6577365 1.6560788 1.647541 ... 1.8561423 1...,"['259', '283', '274', '324', '710', '313', '30...",[0.5765201 0.5707241 0.56797355 0.56728077 0...,"['1723', '1653', '1713', '1718', 'ת', '1716', ...",[0.6439804 0.6395672 0.63701016 0.6347433 0...,a unit of pressure: the pressure that will sup...,atm,[压力单位]
8002,"['russia', 'iran', 'kazakhstan', 'germany', 'j...",[1.025749 1.02863 1.0281837 ... 1.2577786 1...,"['iran', 'uzbekistan', 'russia', 'tajikistan',...",[0.69508606 0.6943106 0.67719984 0.6717092 0...,"['kyrgyzstan', 'tajikistan', 'uzbekistan', '16...",[0.7544387 0.7529264 0.74376136 0.7279767 0...,a republic in Asia to the east of the Caspian ...,turkmenistan,[]
8013,"['seven', 'several', 'three', 'six', 'five', '...",[1.499362 1.4909792 1.4880469 ... 1.6759906 1...,"['321', '239', '271', '252', '269', '259', '23...",[0.6539501 0.6492094 0.6489255 0.64830536 0...,"['billion', 'billions', 'crore', '[unused266]'...",[0.8128726 0.7426422 0.67403865 0.65146506 0...,a very large indefinite number (usually hyperb...,trillion,[庞大的数字]
8510,"['prince', 'james', 'charles', 'richard', 'pri...",[1.3041534 1.303813 1.3068378 ... 1.4896134 1...,"['1682', '1711', '1661', '1663', 'ᄐ', '1762', ...",[0.5843822 0.58196133 0.580834 0.58029985 0...,"['1679', '1690', '1682', '1746', '1760', '1756...",[0.6856004 0.6841308 0.6835112 0.6804766 0...,"formerly, the eldest son of the King of France...",dauphin,[]
9407,"['chinese', 'china', 'japanese', 'spanish', '1...",[1.3718469 1.3744493 1.3787482 ... 1.5363977 1...,"['taiwanese', 'cambodian', 'chinese', 'shangha...",[0.57281506 0.57059157 0.5678443 0.5674057 0...,"['1761', '1757', '1729', '1758', '1759', '1720...",[0.66298604 0.6600502 0.65732783 0.6566536 0...,the dialect of Chinese spoken in Canton and ne...,yue,[]
9548,"['care', 'hospital', 'soldiers', 'medical', 't...",[1.2253594 1.2244415 1.2212381 ... 1.3965738 1...,"['nursing', 'healthcare', 'hospitals', 'medica...",[0.5757751 0.56929207 0.55544406 0.54486614 0...,"['tended', 'tends', 'tend', '1726', 'attends',...",[0.7855295 0.7726491 0.71450806 0.64863205 0...,the work of providing treatment for or attendi...,tending,"[援助, 注意]"
9730,"['league', 'team', 'city', 'american', 'town',...",[1.9463525 1.9437327 1.9488257 ... 2.0112314 2...,"['341', 'railroads', '1721', 'railroad', '219'...",[0.34405944 0.34255996 0.3376153 0.33564445 0...,"['majors', '1664', 'juveniles', '1697', 'youth...",[0.6495576 0.6338878 0.6329181 0.6288123 0...,a league of teams that do not belong to a majo...,minors,[]
9731,"['italy', 'italian', 'fifth', '1985', 'seventh...",[1.4078794 1.4021201 1.3950399 ... 1.5440884 1...,"['35th', '31st', '33rd', 'italy', '355', 'tusc...",[0.55092126 0.55048245 0.55041134 0.54427356 0...,"['1679', '1659', '1718', '1664', '1702', '1756...",[0.7210366 0.71871465 0.71704686 0.7167509 0...,a region of southern Italy (forming the toe of...,calabria,[]
10132,"['william', 'james', 'john', 'robert', 'richar...",[1.1554921 1.1527452 1.1513276 ... 1.3061643 1...,"['335', '1716', '321', '209', '307', '324', '2...",[0.612382 0.6107573 0.60850745 0.6081588 0...,"['robbers', '[unused955]', '[unused401]', '[un...",[0.5870988 0.5568417 0.55673736 0.55633193 0...,United States physicist (born in Hungary) who ...,teller,[]
10239,"['april', 'february', 'september', 'november',...",[2.9721704 2.9927282 2.9663124 ... 2.9770985 2...,"['february', 'september', 'november', 'october...",[0.71353024 0.71119314 0.7110948 0.7086001 0...,"['1829', 'feb', '1796', '1641', '1634', '255',...",[0.6387927 0.63680696 0.6347974 0.6337694 0...,the month following March and preceding May,apr,"[4月, 四月, ４月]"
10609,"['jackson', 'william', 'wilson', 'williams', '...",[1.0624406 1.0637832 1.0496712 ... 1.2349238 1...,"['1785', '1738', '1720', '1765', '1735', '1760...",[0.6222341 0.62061954 0.62054956 0.62040126 0...,"['1709', '1734', '1733', '1732', '1713', '1718...",[0.64699584 0.64438164 0.6427178 0.6421172 0...,British politician (born in the United States)...,astor,[阿斯特，南希·威彻尔·兰霍恩]
11349,"['oklahoma', 'tennessee', 'illinois', 'texas',...",[0.99261534 0.9994888 0.9890601 ... 1.253179...,"['tennessee', 'nebraska', 'illinois', 'iowa', ...",[0.715519 0.68433726 0.6810708 0.67972183 0...,"['1738', '1747', '31st', '1739', '1779', '1741...",[0.6911524 0.6755112 0.6749358 0.6723639 0...,a state in east central United States,tn,[]
11661,"['hindi', 'sanskrit', 'ड', 'spanish', 'chinese...",[0.96560174 0.9708162 0.970812 ... 1.167907...,"['hindi', 'gujarati', 'marathi', 'च', 'pandit'...",[0.6843453 0.662555 0.65559804 0.6534444 0...,"['1695', '1679', '1710', '1692', '1675', '1685...",[0.63798976 0.616087 0.6149999 0.6137635 0...,an ancient Prakrit language (derived from Sans...,pali,[]
11819,"['soldiers', 'ships', 'troops', 'navy', 'numer...",[1.0838646 1.078771 1.0730312 ... 1.2908273 1...,"['1784', '1780', '1778', '1717', '1797', '1781...",[0.6147896 0.6102962 0.608725 0.6072667 0...,"['1665', 'fleets', '1642', '1641', '1646', '16...",[0.6562248 0.6558402 0.65552396 0.6478609 0...,a large fleet,armada,[舰队]
11829,"['chairman', 'headmaster', 'mayor', 'professor...",[1.1127311 1.1073498 1.1013576 ... 1.2681983 1...,"['rector', 'conductor', 'organist', 'keyboardi...",[0.6217942 0.61878484 0.61533374 0.60767543 0...,"['1779', '1778', '1752', '1764', 'rabbis', '16...",[0.64705646 0.6419777 0.64152884 0.6403357 0...,the musical director of a choir,cantor,[]
11903,"['soldiers', '1967', 'william', 'wood', 'brick...",[1.4757872 1.4680858 1.4792066 ... 1.617209 1...,"['279', '231', '252', '267', '229', '259', '23...",[0.53349805 0.53152686 0.530518 0.5301439 0...,"['[unused880]', '[unused237]', '[unused212]', ...",[0.609091 0.60761774 0.606464 0.6064219 0...,the clay from which adobe bricks are made,adobe,"[多孔粘土, 干盐湖粘土, 灰质粘土, 重粘土]"
11951,"['12th', '14th', '1913', '16th', '13th', '10th...",[0.94125843 0.9404469 0.938355 ... 1.137565...,"['57th', '33rd', '1705', '35th', '1756', '55th...",[0.70032513 0.6990083 0.6966379 0.69500524 0...,"['1682', '1621', '1626', '1751', '1642', '1746...",[0.6583102 0.6532928 0.65191907 0.65141606 0...,a deceptive maneuver (especially to avoid capt...,ruse,[]
12104,"['irish', 'french', 'scottish', 'german', 'ita...",[1.2472273 1.2479956 1.2525156 ... 1.4076557 1...,"['irish', 'welsh', 'scottish', 'portuguese', '...",[0.63319516 0.63115776 0.62518185 0.58066195 0...,"['ᄅ', 'চ', '1679', '1680', '1790', '1650', '16...",[0.61508125 0.604335 0.60211766 0.6000785 0...,a Gaelic-speaking Celt in Ireland or Scotland ...,gael,[]
12170,"['beijing', 'russia', 'china', 'russian', 'mos...",[1.0512257 1.0526085 1.052964 ... 1.2579814 1...,"['kazakh', 'kazakhstan', 'mongolian', 'uzbekis...",[0.6612262 0.65443337 0.6516474 0.65097106 0...,"['sichuan', 'yunnan', '[unused192]', '[unused2...",[0.7235814 0.72243345 0.7130318 0.71238226 0...,an autonomous province in far northwestern Chi...,xinjiang,[]
12436,"['want', 'create', 'desire', 'william', 'need'...",[1.0958372 1.0912595 1.0896908 ... 1.2328441 1...,"['1683', 'craving', '1634', '1734', '1680', '1...",[0.5841856 0.57684445 0.5724766 0.5701716 0...,"['1721', '1709', '1654', '1717', '1718', '1716...",[0.6312416 0.62210816 0.6185441 0.61820143 0...,a yearning for something or to do something,yen,[]
12727,"['wilson', '1986', '1985', 'william', '1983', ...",[1.010577 1.0208203 1.0138724 ... 1.2163081 1...,"['1626', '1828', '1611', '1822', '1624', '1635...",[0.6403755 0.6387762 0.63790023 0.6370436 0...,"['1635', '1620', '1621', '1630', '35th', '1638...",[0.6564632 0.65366566 0.6507129 0.6499043 0...,United States comedian; one of four brothers w...,chico,[]
13057,"['seventh', 'eight', 'twelve', 'seven', '##8',...",[1.524696 1.5159507 1.522338 ... 1.7588986 1...,"['1820', '1683', '1759', '1819', '1670', '1770...",[0.5543766 0.55094606 0.5463104 0.54370695 0...,"['1683', '1672', '1695', '1738', '1670', '1781...",[0.6357764 0.6298016 0.62674314 0.62104326 0...,a light curved skeleton to spread out a skirt,hoop,"[圈, 撑裙箍, 箍]"
13180,"['james', 'william', 'wilson', 'johnson', 'ric...",[0.9132066 0.9167483 0.9070531 ... 1.127101 1...,"['1697', '322', '1738', '1734', '1742', '1743'...",[0.70138353 0.7012018 0.69714314 0.695155 0...,"['1682', 'tatar', '1605', '1638', '1611', '163...",[0.67854136 0.67646205 0.67511237 0.67238045 0...,United States stage and screen director (born ...,kazan,[]
13738,"['leipzig', 'stuttgart', 'munich', 'dortmund',...",[1.4491506 1.4418395 1.4361799 ... 1.9188273 1...,"['stuttgart', 'dortmund', 'munich', 'karlsruhe...",[0.7356064 0.73514235 0.73075914 0.73066956 0...,"['1732', '1819', '1746', '1731', '1736', '1664...",[0.7160017 0.70896024 0.7062677 0.70591456 0...,a city in western Germany; industrial center o...,essen,[]
13747,"['australian', 'japanese', 'asian', 'chinese',...",[1.3967979 1.3986529 1.3906065 ... 1.6222663 1...,"['australian', 'japanese', 'indonesian', 'iran...",[0.6429057 0.6299606 0.62330127 0.6231159 0...,"['1842', '1664', '1746', '1823', '1762', '1855...",[0.684379 0.67784786 0.6758293 0.67316794 0...,a native or inhabitant of Asia,asiatic,[亚洲人]
14403,"['guitar', 'violin', '14th', 'ninth', 'musicia...",[1.0051014 1.0081961 1.0077063 ... 1.1740048 1...,"['trumpeter', 'trumpet', '1682', 'violin', '17...",[0.67131805 0.6706684 0.66947484 0.66807085 0...,"['1738', '1732', '1734', '1741', '1743', '1742...",[0.7401216 0.7205515 0.7202167 0.71991 0...,the lowest brass wind instrument,tuba,[大号]

In [432]:
reorder_df = filter_numbers_df[['word', 'translate', 'definition', 'norm_recall', 'original_recall']]

reorder_df = reorder_df.rename(columns={"word": "单词", "translate": "翻译", "definition": "字典释义", "norm_recall": "新召回", "original_recall": "原始召回"})

In [445]:
reorder_df.norm_recall = reorder_df.norm_recall.apply(lambda x: x.split(',')[:5])

AttributeError: 'list' object has no attribute 'strip'

In [448]:
reorder_df.original_recall = reorder_df.original_recall.apply(lambda x: x.split(',')[:5])

/diskb/houbowei/anaconda3/lib/python3.8/site-packages/pandas/core/generic.py:5494: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

In [462]:
def clean_format(x):
    return ''.join([i.strip('[]') for i in x])
reorder_df.original_recall = reorder_df.original_recall.apply(clean_format)
reorder_df.norm_recall = reorder_df.norm_recall.apply(clean_format)

/diskb/houbowei/anaconda3/lib/python3.8/site-packages/pandas/core/generic.py:5494: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

In [464]:
reorder_df.to_csv('final.csv')